---
- name: Clone BlueIris and JellyFin VMs in vCenter
  hosts: localhost
  gather_facts: no
  collections:
    - community.vmware

  vars:
    datacenter_name: "Datacenter"
    datastore_name: "Backup_1"
    vm_folder: "vm" 
    date_suffix: "{{ lookup('pipe', 'date +%m%d%Y') }}"
    vms_to_clone:
      - { template: "BlueIris",  name: "BlueIris_Backup" }
      - { template: "JellyFin",  name: "JellyFin_Backup" }

  tasks:
    - name: Clone VMs in vCenter
      vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        datacenter: "{{ datacenter_name }}"
        folder: "{{ vm_folder }}"  
        name: "{{ item.base_name }}{{ date_suffix }}"
        template: "{{ item.template }}"
        datastore: "{{ datastore_name }}"
        state: poweredoff
      loop: "{{ vms_to_clone }}"
