---
- name: Create ansibleservice user
  hosts: web_servers
  gather_facts: no
  tasks:
    - name: Ensure 'ansibleservice' user is present
      win_user:
        name: ansibleservice
        password: "{{ lookup('env', 'SERVICE_PASSWORD') }}"
        state: present
        update_password: always
        groups:
          - Administrators
        password_never_expires: yes
      vars:
        ansible_user: "{{ lookup('env', 'SERVICE_USERNAME') }}"
