---
- name: Create ansibleservice user
  hosts: web_servers
  gather_facts: no
  tasks:
    - name: Ensure 'ansibleservice' user is present
      win_user:
        name: ansibleservice
        password: "{{ lookup('env', 'ANSIBLE_PASSWORD') }}"
        state: present
        update_password: always
        # Ensure the user is part of the local Administrators group if needed
        groups:
          - Administrators
        password_never_expires: yes
      vars:
        ansible_user: "{{ lookup('env', 'ANSIBLE_USERNAME') }}"
