---
- name: Unmount, Detach, and Forget Disk from ESXi 7 Host
  hosts: esxi
  gather_facts: no
  tasks:

    - name: Ensure the datastore is unmounted
      community.vmware.vmware_host_vmfs:
        hostname: "{{ esxi_hostname }}"
        username: "{{ esxi_username }}"
        password: "{{ esxi_password }}"
        validate_certs: no
        state: unmounted
        datastore: "{{ datastore_name }}"
      delegate_to: localhost
      register: vmfs_unmount_result
      ignore_errors: yes

    - name: Show result of unmount operation
      debug:
        var: vmfs_unmount_result

    - name: Detach the disk from ESXi host
      community.vmware.vmware_host_disk:
        hostname: "{{ esxi_hostname }}"
        username: "{{ esxi_username }}"
        password: "{{ esxi_password }}"
        validate_certs: no
        state: absent
        disk: "{{ disk_device }}"
      delegate_to: localhost
      register: disk_detach_result

    - name: Show result of disk detach operation
      debug:
        var: disk_detach_result

    - name: Forget the disk from ESXi host configuration
      community.vmware.vmware_host_scsi_lun:
        hostname: "{{ esxi_hostname }}"
        username: "{{ esxi_username }}"
        password: "{{ esxi_password }}"
        validate_certs: no
        state: absent
        lun_id: "{{ disk_lun_id }}"
      delegate_to: localhost
      register: disk_forget_result

    - name: Show result of disk forget operation
      debug:
        var: disk_forget_result
