---
- name: Connect to Hyper-V hosts and list VMs
  hosts: hyperv
  gather_facts: no
  collections:
    - community.windows

  tasks:
    - name: Test connection to host
      win_ping:

    - name: List all Hyper-V VMs
      hyperv_guest_info:
      register: hyperv_vms

    - name: Show VM list
      debug:
        var: hyperv_vms.guests
