---
- name: Hyper-V Test Playbook for Semaphore
  hosts: hyperv
  gather_facts: no

  tasks:
    - name: List all Hyper-V VMs
      community.windows.hyperv_guest_info:
      register: hyperv_vms

    - name: Show VM list
      debug:
        var: hyperv_vms.guests
