- name: Mount VMFS datastore to ESXi host
  hosts: localhost
  gather_facts: false
  collections:
    - community.vmware

  vars:
    datastore_name: "Backup_1"
    vmfs_device_name: "naa.5000c50079286feb"

  tasks:
    - name: Mount datastore "{{ datastore_name }}"
      community.vmware.vmware_host_datastore:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: false
        esxi_hostname: "{{ esxi_hostname }}"
        datastore_name: "{{ datastore_name }}"
        vmfs_device_name: "{{ vmfs_device_name }}"
        datastore_type: vmfs
        state: present
