---
- name: Attach disks starting with naa.5000
  hosts: localhost
  gather_facts: false

  vars:
    esxi_hostname: "{{ esxi_hostname }}"
    esxi_user: "{{ esxi_user }}"
    esxi_password: "{{ esxi_password }}"
    validate_certs: false

  tasks:
    - name: Get all VMFS datastores
      community.vmware.vmware_datastore_info:
        hostname: "{{ esxi_hostname }}"
        username: "{{ esxi_user }}"
        password: "{{ esxi_password }}"
        validate_certs: "{{ validate_certs }}"
      register: datastore_info

    - name: Filter disks with naa.5000 prefix
      set_fact:
        naa_disks: "{{ datastore_info.datastores | selectattr('url', 'search', 'naa.5000') | list }}"

    - name: Mount naa.5000 disks as datastores
      community.vmware.vmware_host_datastore:
        hostname: "{{ esxi_hostname }}"
        username: "{{ esxi_user }}"
        password: "{{ esxi_password }}"
        validate_certs: "{{ validate_certs }}"
        datastore_name: "{{ item.name }}"
        state: present
      loop: "{{ naa_disks }}"
