---
- name: Mount Backup datastores on ESXi
  hosts: localhost
  gather_facts: false

  vars:
    esxi_hostname: "{{ esxi_hostname }}"
    esxi_user: "{{ esxi_user }}"
    esxi_password: "{{ esxi_password }}"

  tasks:
    - name: Get list of datastores on the ESXi host
      community.vmware.vmware_datastore_info:
        hostname: "{{ esxi_hostname }}"
        username: "{{ esxi_user }}"
        password: "{{ esxi_password }}"
        validate_certs: false
      register: datastore_info

    - name: Filter datastores with names starting with 'Backup'
      set_fact:
        backup_datastores: "{{ datastore_info.datastores | selectattr('name', 'match', '^Backup.*') | list }}"

    - name: Mount Backup datastores
      community.vmware.vmware_host_datastore:
        hostname: "{{ esxi_hostname }}"
        username: "{{ esxi_user }}"
        password: "{{ esxi_password }}"
        validate_certs: false
        datastore_name: "{{ item.name }}"
        state: present
      loop: "{{ backup_datastores }}"
