---
- name: Attach/mount Backup datastores on ESXi
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Get list of all datastores on the ESXi host
      community.vmware.vmware_datastore_info:
        hostname: "{{ esxi_hostname }}"
        username: "{{ esxi_user }}"
        password: "{{ esxi_password }}"
        validate_certs: false
      register: datastore_info

    - name: Get list of currently mounted datastores
      community.vmware.vmware_host_datastore_facts:
        hostname: "{{ esxi_hostname }}"
        username: "{{ esxi_user }}"
        password: "{{ esxi_password }}"
        validate_certs: false
      register: mounted_info

    - name: Filter Backup datastores that are not currently mounted
      set_fact:
        backup_unmounted_datastores: >-
          {{
            datastore_info.datastores
            | selectattr('name', 'match', '^Backup.*')
            | reject('extract', 'name', mounted_info.datastores | map(attribute='name') | list)
            | list
          }}

    - name: Attach/mount Backup datastores
      community.vmware.vmware_host_datastore:
        hostname: "{{ esxi_hostname }}"
        username: "{{ esxi_user }}"
        password: "{{ esxi_password }}"
        validate_certs: false
        datastore_name: "{{ item.name }}"
        state: present
      loop: "{{ backup_unmounted_datastores }}"
