version: v1.0
name: Ping Test Pipeline

# Define your pipelines
pipelines:
  branches:
    main:
      - name: Test Ping from Ubuntu to Windows
        task:
          jobs:
            - name: Run Ping Test
              environment_variables:
                # Use the variable from the variable group
                WINDOWS_IP: ${WINDOWS_TEST_IP}
              commands:
                - echo "Starting the Ping Test"
                - chmod +x ping-test.sh
                - ./ping-test.sh
