---
- name: Uninstall Google Chrome from web servers
  hosts: web_servers
  become: yes
  tasks:
    - name: Check if Chrome is installed (for debian-based systems)
      command: dpkg -l | grep google-chrome
      register: chrome_installed
      failed_when: false
      changed_when: false

    - name: Uninstall Chrome on Debian-based systems
      apt:
        name: google-chrome-stable
        state: absent
      when: chrome_installed.stdout != ""
      notify:
        - Clean up unused packages

    - name: Check if Chrome is installed (for rpm-based systems)
      command: rpm -qa | grep google-chrome
      register: chrome_installed_rpm
      failed_when: false
      changed_when: false

    - name: Uninstall Chrome on RPM-based systems
      yum:
        name: google-chrome-stable
        state: absent
      when: chrome_installed_rpm.stdout != ""
      notify:
        - Clean up unused packages

  handlers:
    - name: Clean up unused packages
      apt:
        autoremove: yes
        autoclean: yes
      when: ansible_facts.packages is defined and ansible_facts.packages is not empty
      become: yes
