
        Get-ItemProperty -Path "HKLM:\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\Google Chrome" | Select-Object -ExpandProperty UninstallString
    ---
- name: Uninstall Google Chrome
  hosts: all
  tasks:
    - name: Find Chrome uninstall command
      win_registry_facts:
        path: 'HKLM:\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\Google Chrome'
    
    - name: Debug Uninstall Command
      debug:
        msg: "{{ registry['HKLM:\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\Google Chrome'].UninstallString }}"

    - name: Run Chrome uninstall
      win_command: "{{ registry['HKLM:\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\Google Chrome'].UninstallString }} /silent"
      args:
        chdir: "C:\\Program Files\\Google\\Chrome\\Application\\"
