---
- name: Uninstall Google Chrome from Windows Server
  hosts: web_servers
  gather_facts: yes

  tasks:
    - name: Find Google Chrome installation registry key
      win_reg_stat:
        path: HKLM:\Software\Microsoft\Windows\CurrentVersion\Uninstall\Google Chrome
      register: chrome_install_key
      ignore_errors: yes

    - name: Uninstall Google Chrome if installed
      win_command: '"C:\\Program Files\\Google\\Chrome\\Application\\chrome_installer.exe" --uninstall --multi-install --chrome --system-level --force-uninstall'
      when: chrome_install_key is defined and chrome_install_key.key is not none

    - name: Verify Google Chrome Uninstallation
      win_stat:
        path: "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe"
      register: chrome_uninstalled

    - name: Check if Chrome was uninstalled
      debug:
        msg: "Google Chrome has been uninstalled successfully!"
      when: not chrome_uninstalled.stat.exists
