---
- name: Uninstall Google Chrome from Windows Server
  hosts: web_servers
  gather_facts: yes

  tasks:
    - name: Find Google Chrome Uninstall String in Registry
      win_reg_facts:
        path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Google Chrome
      register: chrome_uninstall_info
      ignore_errors: yes

    - name: Uninstall Google Chrome using registry uninstall string
      win_command: "{{ chrome_uninstall_info.ansible_facts['winreg']['HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\Google Chrome']['UninstallString'] }} /silent"
      when: chrome_uninstall_info.ansible_facts['winreg']['HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\Google Chrome'] is defined

    - name: Verify Google Chrome Uninstallation
      win_stat:
        path: "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe"
      register: chrome_uninstalled

    - name: Check if Chrome was uninstalled
      debug:
        msg: "Google Chrome has been uninstalled successfully!"
      when: not chrome_uninstalled.stat.exists
