---
- name: Unmount and Detach Datastore and Disk
  hosts: localhost
  gather_facts: no
  collections:
    - community.vmware
  vars:
    datastore_name: "Backup_1"
    vmfs_device_name: "naa.5000c50079286feb"
  tasks:
    - name: Unmount datastore
      vmware_host_datastore:
        hostname: "{{ esxi_host }}"
        username: "{{ esxi_user }}"
        password: "{{ esxi_password }}"
        validate_certs: no
        datastore_name: "{{ datastore_name }}"
        state: absent

    - name: Detach disk from host
      vmware_host_storage:
        hostname: "{{ esxi_host }}"
        username: "{{ esxi_user }}"
        password: "{{ esxi_password }}"
        validate_certs: no
        device_names:
          - "{{ vmfs_device_name }}"
        detach: true
        esxi_hostname: "{{ esxi_host }}"
