- name: Unmount and Detach Datastore and Disk
  hosts: localhost
  gather_facts: no
  vars:
    datastore_name: "Backup_1"  # Name of the datastore to unmount
    vmfs_device_name: "naa.5000c50079286feb"  # Device name of the disk
  tasks:
    - name: Unmount datastore 
      community.vmware.vmware_host_datastore:
        hostname: "{{ esxi_host }}"
        username: "{{ esxi_user }}"
        password: "{{ esxi_password }}"
        validate_certs: no
        datastore_name: "{{ datastore_name }}"
        state: "absent"

    - name: Detach disk 
      community.vmware.vmware_host_disk:
        hostname: "{{ esxi_host }}"
        username: "{{ esxi_user }}"
        password: "{{ esxi_password }}"
        validate_certs: no
        device_name: "{{ vmfs_device_name }}"
        state: "absent"
