---
- name: Unmount and detach datastores starting with 'Backup' on ESXi
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Get list of datastores on the ESXi host
      community.vmware.vmware_datastore_info:
        hostname: "{{ esxi_hostname }}"
        username: "{{ esxi_user }}"
        password: "{{ esxi_password }}"
        validate_certs: false
      register: datastore_info

    - name: Filter datastores starting with 'Backup'
      set_fact:
        backup_datastores: "{{ datastore_info.datastores | selectattr('name', 'match', '^Backup.*') | list }}"

    - name: Unmount Backup datastores
      community.vmware.vmware_host_datastore:
        hostname: "{{ esxi_hostname }}"
        username: "{{ esxi_user }}"
        password: "{{ esxi_password }}"
        validate_certs: false
        datastore_name: "{{ item.name }}"
        state: unmounted
      loop: "{{ backup_datastores }}"

    - name: Detach Backup datastores
      community.vmware.vmware_host_datastore:
        hostname: "{{ esxi_hostname }}"
        username: "{{ esxi_user }}"
        password: "{{ esxi_password }}"
        validate_certs: false
        datastore_name: "{{ item.name }}"
        state: detached
      loop: "{{ backup_datastores }}"
