---
- name: Clone VM to another datastore and remove from inventory
  hosts: localhost
  gather_facts: no
  vars:
    source_vm: "Test2"
    clone_vm: "Test2-Backup"
    target_datastore: "Backup_1"
    validate_certs: no

  tasks:
    - name: Clone the VM to a new datastore
      community.vmware.vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: "{{ validate_certs }}"
        name: "{{ clone_vm }}"
        template: no
        state: poweredoff
        datastore: "{{ target_datastore }}"
        folder: "/"
        clone:
          name: "{{ clone_vm }}"
          template: false
          source: "{{ source_vm }}"
          power_on: false

    - name: Remove cloned VM from inventory
      community.vmware.vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: "{{ validate_certs }}"
        name: "{{ clone_vm }}"
        state: absent
        delete_from_disk: false
