---
- name: Clone VM and remove from inventory (ESXi host)
  hosts: localhost
  gather_facts: no
  vars:
    source_vm: "Test2"
    clone_vm: "Test2-Backup"
    target_datastore: "Backup_1"
    validate_certs: no

  tasks:
    - name: Clone VM to a new datastore
      community.vmware.vmware_guest:
        hostname: "{{ esxi_hostname }}"
        username: "{{ esxi_username }}"
        password: "{{ esxi_password }}"
        validate_certs: "{{ validate_certs }}"
        name: "{{ clone_vm }}"
        template: false
        template_src: "{{ source_vm }}"
        datastore: "{{ target_datastore }}"
        folder: "/"
        state: poweredoff
        esxi_hostname: "{{ esxi_hostname }}"

    - name: Remove cloned VM from inventory
      community.vmware.vmware_guest:
        hostname: "{{ esxi_hostname }}"
        username: "{{ esxi_username }}"
        password: "{{ esxi_password }}"
        validate_certs: "{{ validate_certs }}"
        name: "{{ clone_vm }}"
        state: absent
        delete_from_disk: false
