---
- name: Windows Update and Reboot
  hosts: web_servers
  gather_facts: no
  tasks:

    - name: Attempt reboot if shutdown is pending
      block:
        - name: Try to reboot
          win_reboot:
          register: reboot_trigger
          ignore_errors: yes

        - name: Wait for system if reboot failed due to shutdown already in progress
          wait_for_connection:
            timeout: 600
            delay: 30
          when: reboot_trigger is failed

    - name: Install all available Windows updates
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
          - UpdateRollups
          - Updates
        reboot: yes
      register: update_result

    - name: Wait for system to become reachable after updates (if rebooted)
      wait_for_connection:
        timeout: 600
        delay: 30
      when: update_result.reboot_required

    - name: Confirm machine is online and responsive
      win_command: 'whoami'
      register: whoami_result

    - name: Print user context of remote system
      debug:
        var: whoami_result.stdout
